### ISSUE TITLE
How to download images locally? 

### ISSUE THREAD

**Issue by arky** [regisphilibert/monsterspotting-remote.com#2]
@regisphilibert Instead of directly hot linking to [images] (https://monsters-api.netlify.app/png_7480160596753705284.png) it is better to download them and save to /static/images. 

Is there a way to achieve this with hugo pipelines? Thanks

**Comment by regisphilibert** [comment]
You can use `resources.GetRemote` to process any "remote" images. (https://gohugo.io/hugo-pipes/introduction/#get-resource-with-resourcesget-and-resourcesgetremote)

From the prebuild project, you could GetRemote the images, process them and `.Publish` them. With `resourses.Copy` you can control where you save them.
Then you can mount that directory in the static directory of your main project.

**Comment by arky** [comment]
Thank you @regisphilibert That answers my question.
